// The AM Fragrances collection the store launches with. These are not read by the
// storefront directly: Admin → Products → "Import the collection" copies them into
// the database, where they can be edited like any other product.
import type { Product } from './catalog';

const size100 = (price: number) => [{ id: '100ml', size: '100 ml', price, mrp: price, inStock: true }];

export const STARTER_PRODUCTS: Product[] = [
  {
    slug: 'royal-oud',
    featured: true,
    name: 'Royal Oud',
    tagline: 'Smoky oud, saffron and warm amber',
    description:
      'A rich, regal eau de parfum built around precious oud. Saffron and cardamom open with a warm glow before a heart of oud wood and Bulgarian rose, settling into sandalwood, amber and soft leather. Deep, smoky and long-lasting — made for evenings and celebrations.',
    gender: 'unisex',
    category: 'perfume',
    concentration: 'Eau de Parfum',
    images: ['/images/am/products/royal-oud.webp'],
    variants: size100(2999),
    notes: { top: ['Saffron', 'Cardamom', 'Bergamot'], heart: ['Oud Wood', 'Bulgarian Rose', 'Patchouli'], base: ['Sandalwood', 'Amber', 'Leather', 'Musk'] },
    longevity: '8–10 hours',
    sillage: 'Strong',
    seasons: ['Autumn', 'Winter'],
    occasions: ['Evening', 'Weddings', 'Festive'],
    releasedAt: '2026-10-01',
  },
  {
    slug: 'midnight-noir',
    name: 'Midnight Noir',
    tagline: 'Black pepper, lavender and dark vanilla',
    description:
      'Dark, magnetic and confident. A spark of black pepper and bergamot gives way to aromatic lavender and smooth iris, resting on a warm base of vanilla, tonka bean and smoky vetiver. A night-time signature that lingers long after you leave.',
    gender: 'men',
    category: 'perfume',
    concentration: 'Eau de Parfum',
    images: ['/images/am/products/midnight-noir.webp'],
    variants: size100(3499),
    notes: { top: ['Black Pepper', 'Bergamot', 'Pink Pepper'], heart: ['Lavender', 'Iris', 'Clary Sage'], base: ['Vanilla', 'Tonka Bean', 'Vetiver', 'Amberwood'] },
    longevity: '8–10 hours',
    sillage: 'Strong',
    seasons: ['Autumn', 'Winter'],
    occasions: ['Night Out', 'Date Night', 'Evening'],
    releasedAt: '2026-10-01',
  },
  {
    slug: 'citrus-wood',
    name: 'Citrus Wood',
    tagline: 'Sparkling bergamot, neroli and cedar',
    description:
      'Fresh, green and effortlessly clean. Sparkling bergamot, lemon and green mandarin open bright, softened by neroli and petitgrain, then settle into dry cedarwood, vetiver and white musk. An easy everyday scent for the office, the outdoors and warm Indian days.',
    gender: 'unisex',
    category: 'perfume',
    concentration: 'Eau de Parfum',
    images: ['/images/am/products/citrus-wood.webp'],
    variants: size100(3999),
    notes: { top: ['Bergamot', 'Lemon', 'Green Mandarin'], heart: ['Neroli', 'Petitgrain', 'Green Tea'], base: ['Cedarwood', 'Vetiver', 'White Musk'] },
    longevity: '6–8 hours',
    sillage: 'Moderate',
    seasons: ['Spring', 'Summer'],
    occasions: ['Daily Wear', 'Office', 'Daytime'],
    releasedAt: '2026-10-01',
  },
  {
    slug: 'ocean-breeze',
    name: 'Ocean Breeze',
    tagline: 'Sea salt, marine notes and driftwood',
    description:
      'Like a cool wind off the sea. Sea salt, bergamot and mint lift into a marine accord with lavender and sage, drying down to sun-warmed driftwood, ambergris and clean musk. Crisp, airy and refreshing — perfect for summer, travel and the gym.',
    gender: 'men',
    category: 'perfume',
    concentration: 'Eau de Parfum',
    images: ['/images/am/products/ocean-breeze.webp'],
    variants: size100(4499),
    notes: { top: ['Sea Salt', 'Bergamot', 'Mint'], heart: ['Marine Accord', 'Lavender', 'Sage'], base: ['Driftwood', 'Ambergris', 'White Musk'] },
    longevity: '6–8 hours',
    sillage: 'Moderate',
    seasons: ['Summer', 'Spring'],
    occasions: ['Daily Wear', 'Travel', 'Sport'],
    releasedAt: '2026-10-01',
  },
  {
    slug: 'velvet-bloom',
    name: 'Velvet Bloom',
    tagline: 'Rose, peony and soft vanilla musk',
    description:
      'Soft, feminine and quietly luxurious. Juicy lychee, pear and pink pepper open into a bouquet of rose, peony and jasmine, wrapped in creamy vanilla, sandalwood and powdery musk. Romantic and elegant from morning to night.',
    gender: 'women',
    category: 'perfume',
    concentration: 'Eau de Parfum',
    images: ['/images/am/products/velvet-bloom.webp'],
    variants: size100(4999),
    notes: { top: ['Lychee', 'Pear', 'Pink Pepper'], heart: ['Rose', 'Peony', 'Jasmine'], base: ['Vanilla', 'Sandalwood', 'White Musk'] },
    longevity: '8–10 hours',
    sillage: 'Moderate',
    seasons: ['Spring', 'Autumn'],
    occasions: ['Date Night', 'Weddings', 'Daily Wear'],
    releasedAt: '2026-10-01',
  },
];
